version: '3'
services:
  app:
    build: .
    image: stitchr-api:v1
    restart: always
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - application
    container_name: stitchr-backend

  db:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - MONGO_INITDB_ROOT_USERNAME
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    networks:
      - application
    container_name: mongodb

networks:
  application:
    driver: bridge

volumes:
  mongo-data:
    driver: local
